.INCLUDE "M328PDEF.INC"

.EQU    MOSI = 3
.EQU    SCK = 5
.EQU    SS1 = 2
.EQU    SS2 = 1

    ;LDI R30, 0XFF
    ;OUT DDRA, R30

    LDI     R30, (1<<MOSI)| (1<<SCK) | ( 1<<SS1) | ( 1<<SS2)
    STS     DDRB, R17; MOSI, SCK, SS1 E SS2 COMO OUTPUT

    LDI     R30, (1<<SPE) | (1<<MSTR); HABILITA SPI
    STS     SPCR, R30 ; ATMEGA MESTRE COM CLOCK = FCK/4

    LDI     R25, HIGH(RAMEND) ;SETA OS 8 BITS MAIS SIGNIFICATIVOS DA PILHA
    STS     SPH, R25 ;PONTEIRO
    LDI     R25, LOW(RAMEND) ;SETA OS 8 BITS MENOS SIGNIFICATIVOS DA PILHA
    STS     SPL, R25 ;PONTEIRO

    LDI     R30, 0X09 ;DECODE MODE DO MAX7221
    LDI     R29, 0B00001111 ;HABILITA O DECODE PARA OS DIGITOS DE 0 A 3
    RCALL   RUNCMD

    LDI     R30, 0X0B ;SCAN LIMIT
    LDI     R29, 0X03 ; SCAN QUATRO DISPLAYS 7SEG
    RCALL   RUNCMD

    LDI     R30, 0X0B ; COMANDO DE LIGA/DESLIGA
    LDI     R29, 0X01 ; LIGA O CI
    RCALL   RUNCMD

RTC_MINUTOS:
    CBI     PORTB, SS1
    LDI     R29, 0X83 ;CARREGA O ENDEREÇO DE LEITURA DOS MINUTOS
    STS     SPDR, R29 ;ENVIAR O ENDEREÇO
    CALL    WAIT_MINUTOS
    MOV     R29, R26
    RCALL   DEZENA

DISPLAY_MINUTOS1:
    LDI     R30, 0X01
    RCALL   RUNCMD

DISPLAY_MINUTOS2:
    LDI     R30, 0X02
    MOV     R29, R28
    RCALL   RUNCMD

RTC_HORAS:
    CBI     PORTB, SS1
    LDI     R29, 0X85 ;CARREGA O ENDEREÇO DE LEITURA DOS MINUTOS
    STS     SPDR, R29 ;ENVIAR O ENDEREÇO
    RCALL   WAIT_HORAS
    MOV     R29, R27
    RCALL   DEZENA

DISLPAY_HORAS1:
    LDI     R30, 0X03
    RCALL   RUNCMD

DISPLAY_HORAS2:
    LDI     R30, 0X04
    MOV     R29, R28
    RCALL   RUNCMD

WAIT_MINUTOS:
    SBIS    SPSR, SPIF ;ESPERA A FLAG DE FIM DE TRANSFERÊNCIA ATIVAR
    RJMP    WAIT_MINUTOS
    IN      R27, SPDR ;LER OS DADOS RECEBIDOS NO REGISTRADOR 29
    ;OUT PORTA, R27

    SBI     PORTB, SS1 ;DESABILITA O SLAVE DEVICE
    RET

WAIT_HORAS:
    SBIS    SPSR, SPIF ;ESPERA A FLAG DE FIM DE TRANSFERÊNCIA ATIVAR
    RJMP    WAIT_HORAS
    IN      R26, SPDR ;LER OS DADOS RECEBIDOS NO REGISTRADOR 29
    ;OUT PORTA, R26

    SBI     PORTB, SS1 ;DESABILITA O SLAVE DEVICE
    RET
    RJMP    RTC_MINUTOS

;TRANSMISSÃO PARA O CI MAX7221
;R30 RECEBE O ENDEREÇO
;R29 RECEBE OS DADOS
RUNCMD:
    CBI     PORTB, SS2 ; COMEÇA A TRANSMISSÃO PARA O DISPLAY DRIVER
    OUT     SPDR, R30

WAIT1:
    SBIS    SPDR, SPIF ;PULA PARA PRÓXIMA INSTRUÇÃO SE SPIF FOR 1
    RJMP    WAIT1

    STS     SPDR, R29

WAIT2:
    SBIS    SPDR, SPIF
    RJMP    WAIT2

    SBI     PORTB, SS2; TERMINA A TRANSMISSÃO
    RET
;FIM DA TRANSMISSÃO

;BIN-BCD
DEZENA:
    CPI     R29, 10
    BRLO    UNIDADE
    SUBI    R29, 10
    INC     R28
    RJMP    DEZENA

UNIDADE: 
    RET