.INCLUDE "M328PDEF.INC"
.ORG 0

;R17 - REG_POINTER
;R18 - REG_TWOF
;R19 - REG_HOUR_R
;R20 - REG_MIN_R
;R21 - REG_WEEK_R
;R22 - REG_HOUR_ON
;R23 - REG_MIN_ON
;R24 - REG_WEEK_ON
;R25 - REG_HOUR_OFF
;R26 - REG_MIN_OFF
;R27 - REG_WEEK_OFF

;--------SETAR ENTRADAS E SAIDAS D-----
;ENTRADAS: PD7, PD6, PD5 (SEGUNDA SAÍDA DA CHAVE, TERCEIRA SAÍDA DA CHAVE, ENTRADA IN DO SISTEMA)
;SAÍDAS:   PD4, PD3, PD2, PD1, PD0 (SAÍDA OUT DO SISTEMA, LED F, LED O, LED W, LED T)
LDI     R16, 0B11111111
OUT     DDRD, R16

;--------SETAR ENTRADAS E SAIDAS B-----
;NÃO USADAS: PB7, PB6, PB1 E PB0
;ENTRADAS USADAS: PB4 (SAÍDA DOUT DO MAX6902)
;SAÍDAS USADAS: PB2, PB3, PB5 (ENTRADA C’S’ DO MAX6902 E ENTRADA C’S’ DO MAX7221, ENTRADA DIN DO MAX6902 E ENTRADA DIN DO MAX7221, ENTRADA SCLK DO MAX6902 E ENTRADA SCLK DO MAX7221)
LDI     R16, 0B11111111
OUT     DDRB, R16

;--------SETAR ENTRADAS E SAIDAS C-----
;NÃO USADA: PC7
;ENTRADAS USADAS: PC0, PC1, PC2, PC3 (BOTÃO DOWN, UP, A, R)
;SAÍDAS USADAS: PC4, PC5, PC6 (ENTRADA A0 DO MC74H328A, ENTRADA A1 DO MC74H328A, ENTRADA A2 DO MC74H328A)
LDI     R16, 0B110000
OUT     DDRC, R16


;--------------------ESTADO START. CONFORME A MDE, A MÁQUINA DÁ CLEAR EM TODOS OS REGISTRADORES USADOS E PRESET
;--------------------NO VALOR DO REGISTRADOR DE DIAS DA SEMANA PARA SELECIONAR O DOMINGO COMO PONTO INICIAL DO
;--------------------PRÓXIMO ESTADO E VAI DIRETO PARA O ESTDAO RUN.------------------------------------------------------
START:
    CLR     R17
    CLR     R18
    CLR     R19
    CLR     R20
    LDI     R21, 0B00000001
    CLR     R22
    CLR     R23
    LDI     R24, 0B00000001
    CLR     R25
    CLR     R26
    LDI     R27, 0B00000001

;----------ESTADO RUN. CHECA SE TÁ NO INTERVALO DE ALARME E MODIFICA O OUT. ALÉM DISSO, CHECA QUAL BOTÃO FOI APERTADO: A OU R--------------------------------
RUN:
    SBIC    PINC, PC3 ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO
    JMP     RUN ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO

    SBIC    PINC, PC2 ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO
    JMP     RUN ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO

RUNEAE:
    ;TESTE LED DE ESTADO--------------------
    SBI     PORTD, PD0 ; TESTE ------------------------------------
    CBI     PORTD, PD1 ; TESTE ------------------------------------
    CBI     PORTC, PC5 ; TESTE ------------------------------------
    CBI     PORTC, PC4 ; TESTE ------------------------------------

;TESTE LED DE HORA RELOGIO--------------------

    SBRC    R19, 0 ;TESTE------------
    SBI     PORTB, PB3;TESTE-----------
    SBRS    R19, 0 ;TESTE------------
    CBI     PORTB, PB3;TESTE-----------

    SBRC R19, 1 ;TESTE------------
    SBI     PORTB, PB4;TESTE-----------
    SBRS    R19, 1 ;TESTE------------
    CBI     PORTB, PB4;TESTE-----------

    SBRC    R19, 2 ;TESTE------------
    SBI     PORTB, PB5;TESTE-----------
    SBRS    R19, 2 ;TESTE------------
    CBI     PORTB, PB5;TESTE-----------

    SBRC    R19, 3 ;TESTE------------
    SBI     PORTB, PB6;TESTE-----------
    SBRS    R19, 3 ;TESTE------------
    CBI     PORTB, PB6;TESTE-----------

    SBRC    R19, 4 ;TESTE------------
    SBI     PORTB, PB7;TESTE-----------
    SBRS    R19, 4 ;TESTE------------
    CBI     PORTB, PB7;TESTE-----------

    ;TESTE LED DE MINUTO RELOGIO--------------------

    SBRC    R20, 0 ;TESTE------------
    SBI     PORTD, PD2;TESTE-----------
    SBRS    R20, 0 ;TESTE------------
    CBI     PORTD, PD2;TESTE-----------

    SBRC    R20, 1 ;TESTE------------
    SBI     PORTD, PD3;TESTE-----------
    SBRS    R20, 1 ;TESTE------------
    CBI     PORTD, PD3;TESTE-----------

    SBRC    R20, 2 ;TESTE------------
    SBI     PORTD, PD4;TESTE-----------
    SBRS    R20, 2 ;TESTE------------
    CBI     PORTD, PD4;TESTE-----------

    SBRC    R20, 3 ;TESTE------------
    SBI     PORTD, PD5;TESTE-----------
    SBRS    R20, 3 ;TESTE------------
    CBI     PORTD, PD5;TESTE-----------

    SBRC    R20, 4 ;TESTE------------
    SBI     PORTD, PD6;TESTE-----------
    SBRS    R20, 4 ;TESTE------------
    CBI     PORTD, PD6;TESTE-----------

    SBRC    R20, 5 ;TESTE------------
    SBI     PORTD, PD7;TESTE-----------
    SBRS    R20, 5 ;TESTE------------
    CBI     PORTD, PD7;TESTE-----------


    ;TESTE LED DE DIA--------------------
    SBRC    R21, 0 ;TESTE------------
    SBI     PORTB, PB0;TESTE-----------
    SBRS    R21, 0 ;TESTE------------
    CBI     PORTB, PB0;TESTE-----------

    SBRC    R21, 1 ;TESTE------------
    SBI     PORTB, PB1;TESTE-----------
    SBRS    R21, 1 ;TESTE------------
    CBI     PORTB, PB1;TESTE-----------

    SBRC    R21, 2 ;TESTE------------
    SBI     PORTB, PB2;TESTE-----------
    SBRS    R21, 2 ;TESTE------------
    CBI     PORTB, PB2;TESTE-----------




    SBIC    PINC, PC2 ; SE O PINO PC2 ESTIVER EM BAIXO, A PRÓXIMA INSTRUÇÃO NÃO É EXECUTADA, OU SEJA, A PESSOA NÃO APERTOU O BOTÃO A
    JMP     AJUSTE_AGENDAMENTO_INICIO ; SE PULOU PARA AQUI, É PQ O O BOTÃO A FOI APERTADO, ENTÃO VAI PARA O AJUSTE DO AGENDAMENTO
    SBIC    PINC, PC3 ; CHEGOU AQUI PQ O BOTAO ANTERIOR NÃO ESTAVA APERTADO. ENTÃO, SE O PINO PC3 ESTIVER NÃO ESTIVER EM ALTO, A PRÓXIMA INSTRUÇÃO NÃO É EXECUTADA, OU SEJA, A PESSOA NÃO APERTOU O BOTÃO R
    JMP     AJUSTE_RELOGIO ; SE PULOU PARA AQUI, É PQ O O BOTÃO R FOI APERTADO, ENTÃO VAI PARA O AJUSTE DO RELÓGIO
    JMP     RUNEAE ; SE CHEGOU AQUI É PQ NEM O BOTÃO A NEM O R FORAM APERTADOS, ENTÃO VOLTA PARA O RUN PARA CHECAR NOVAMENTE.



;----ESTADO DE AJUSTE DE RELÓGIO, SÓ CHEGOU AQUI SE O PC3 (BOTÃO R) ESTAVA ATIVO--------------
AJUSTE_RELOGIO:
    JMP TIMER_H

;----ESTADO DE AJUSTE DO INICIO DO AGENDAMENTO, SÓ CHEGOU AQUI SE O PC2 (BOTÃO A) ESTAVA ATIVO--------------
AJUSTE_AGENDAMENTO_INICIO:
;LIMPAR OS LEDS DE TESYE
    CBI     PORTD, PD0 ; TESTE-----------
    CBI     PORTD, PD1 ; TESTE-----------
    CBI     PORTD, PD2 ; TESTE-----------
    CBI     PORTD, PD3 ; TESTE-----------
    CBI     PORTD, PD4 ; TESTE-----------
    CBI     PORTD, PD5 ; TESTE-----------
    CBI     PORTD, PD6 ; TESTE-----------
    CBI     PORTD, PD7 ; TESTE-----------
    SBI     PORTB, PB0 ; TESTE-----------
    CBI     PORTB, PB1 ; TESTE-----------   
    CBI     PORTB, PB2 ; TESTE-----------
    CBI     PORTB, PB3 ; TESTE-----------
    CBI     PORTB, PB4 ; TESTE-----------
    CBI     PORTB, PB5 ; TESTE-----------
    CBI     PORTB, PB6 ; TESTE-----------
    CBI     PORTB, PB7 ; TESTE-----------
    CBI     PORTC, PC4 ; TESTE-----------
    CBI     PORTC, PC5 ; TESTE-----------
    JMP     ON_H


;----ESTADO DE AJUSTE DO FIM DO AGENDAMENTO--------------
AJUSTE_AGENDAMENTO_FIM:

;LIMPAR OS LEDS DE TESYE
    CBI     PORTD, PD0 ; TESTE-----------
    CBI     PORTD, PD1 ; TESTE-----------
    CBI     PORTD, PD2 ; TESTE-----------
    CBI     PORTD, PD3 ; TESTE-----------
    CBI     PORTD, PD4 ; TESTE-----------
    CBI     PORTD, PD5 ; TESTE-----------
    CBI     PORTD, PD6 ; TESTE-----------
    CBI     PORTD, PD7 ; TESTE-----------
    SBI     PORTB, PB0 ; TESTE-----------
    CBI     PORTB, PB1 ; TESTE-----------
    CBI     PORTB, PB2 ; TESTE-----------
    CBI     PORTB, PB3 ; TESTE-----------
    CBI     PORTB, PB4 ; TESTE-----------
    CBI     PORTB, PB5 ; TESTE-----------
    CBI     PORTB, PB6 ; TESTE-----------
    CBI     PORTB, PB7 ; TESTE-----------
    CBI     PORTC, PC4 ; TESTE-----------
    CBI     PORTC, PC5 ; TESTE-----------
    JMP     OFF_H




TIMER_H:
    SBIC PINC, PC3 ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO
    RJMP TIMER_H ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    CBI PORTD, PD0 ; TESTE ------------------------------------
    SBI PORTD, PD1 ; TESTE ------------------------------------
    CBI PORTC, PC5 ; TESTE ------------------------------------
    CBI PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE HORA RELOGIO--------------------

    SBRC    R19, 0 ;TESTE------------
    SBI     PORTB, PB3;TESTE-----------
    SBRS    R19, 0 ;TESTE------------
    CBI     PORTB, PB3;TESTE-----------

    SBRC    R19, 1 ;TESTE------------
    SBI     PORTB, PB4;TESTE-----------
    SBRS    R19, 1 ;TESTE------------
    CBI     PORTB, PB4;TESTE-----------

    SBRC    R19, 2 ;TESTE------------
    SBI     PORTB, PB5;TESTE-----------
    SBRS    R19, 2 ;TESTE------------
    CBI     PORTB, PB5;TESTE-----------

    SBRC    R19, 3 ;TESTE------------
    SBI     PORTB, PB6;TESTE-----------
    SBRS    R19, 3 ;TESTE------------
    CBI     PORTB, PB6;TESTE-----------

    SBRC    R19, 4 ;TESTE------------
    SBI     ORTB, PB7;TESTE-----------
    SBRS    R19, 4 ;TESTE------------
    CBI     PORTB, PB7;TESTE-----------

TIMER_HEAE:
    LDI     R17, 0B00000001 ; VALOR DO PONTEIRO DO TIMER_H
    SBIC    PINC, PC3 ; CHECA: SE O BOTÃO R NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     TIMER_M ; SE CHEGOU AQUI É PQ APERTOU O BOTAO R, ENTAO VAI PRA O PROXIMO ESTADO DA SEQUENCIA DE AJUSTE DO RELOGIO
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     TIMER_HEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR


TIMER_M:
    SBIC PINC, PC3 ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO
    RJMP TIMER_M ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO


    ;TESTE LED DE ESTADO--------------------
    SBI PORTD, PD0 ; TESTE ------------------------------------
    SBI PORTD, PD1 ; TESTE ------------------------------------
    CBI PORTC, PC5 ; TESTE ------------------------------------
    CBI PORTC, PC4 ; TESTE ------------------------------------


    ;TESTE LED DE MINUTO RELOGIO--------------------

    SBRC    R20, 0 ;TESTE------------
    SBI     PORTD, PD2;TESTE-----------
    SBRS    R20, 0 ;TESTE------------
    CBI     PORTD, PD2;TESTE-----------

    SBRC    R20, 1 ;TESTE------------
    SBI     PORTD, PD3;TESTE-----------
    SBRS    R20, 1 ;TESTE------------
    CBI     PORTD, PD3;TESTE-----------

    SBRC    R20, 2 ;TESTE------------
    SBI     PORTD, PD4;TESTE-----------
    SBRS    R20, 2 ;TESTE------------
    CBI     PORTD, PD4;TESTE-----------

    SBRC    R20, 3 ;TESTE------------
    SBI     PORTD, PD5;TESTE-----------
    SBRS    R20, 3 ;TESTE------------
    CBI     PORTD, PD5;TESTE-----------

    SBRC    R20, 4 ;TESTE------------
    SBI     PORTD, PD6;TESTE-----------
    SBRS    R20, 4 ;TESTE------------
    CBI     PORTD, PD6;TESTE-----------

    SBRC    R20, 5 ;TESTE------------
    SBI     PORTD, PD7;TESTE-----------
    SBRS    R20, 5 ;TESTE------------
    CBI     PORTD, PD7;TESTE-----------

TIMER_MEAE:
    LDI     R17, 0B00000010
    SBIC    PINC, PC3 ; CHECA: SE O BOTÃO R NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     WEEK ; SE CHEGOU AQUI É PQ APERTOU O BOTAO R, ENTAO VAI PRA O PROXIMO ESTADO DA SEQUENCIA DE AJUSTE DO RELOGIO
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     TIMER_MEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

WEEK:
    SBIC    PINC, PC3 ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO
    JMP     WEEK ; SO PRA GARANTIR QUE O BOTAO R FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    CBI     PORTD, PD0 ; TESTE ------------------------------------
    CBI     PORTD, PD1 ; TESTE ------------------------------------
    SBI     PORTC, PC5 ; TESTE ------------------------------------
    CBI     PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE DIA--------------------
    SBRC    R21, 0 ;TESTE------------
    SBI     PORTB, PB0;TESTE-----------
    SBRS    R21, 0 ;TESTE------------
    CBI     PORTB, PB0;TESTE-----------

    SBRC    R21, 1 ;TESTE------------
    SBI     PORTB, PB1;TESTE-----------
    SBRS    R21, 1 ;TESTE------------
    CBI     PORTB, PB1;TESTE-----------

    SBRC    R21, 2 ;TESTE------------
    SBI     PORTB, PB2;TESTE-----------
    SBRS    R21, 2 ;TESTE------------
    CBI     PORTB, PB2;TESTE-----------

WEEKEAE:
    LDI     R17, 0B00000011
    SBIC    PINC, PC3 ; CHECA: SE O BOTÃO R NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     RUN ; SE CHEGOU AQUI É PQ APERTOU O BOTAO R, ENTAO ACABOU O AJUSTE DE RELOGIO E VOLTA PRO RUN
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     WEEKEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

ON_H:
    SBIC    PINC, PC2 ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO
    JMP     ON_H ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    SBI     PORTD, PD0 ; TESTE ------------------------------------
    CBI     PORTD, PD1 ; TESTE ------------------------------------
    SBI     PORTC, PC5 ; TESTE ------------------------------------
    CBI     PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE HORA AGENDAMENTO INICIO--------------------

    SBRC    R22, 0 ;TESTE------------
    SBI     PORTB, PB3;TESTE-----------
    SBRS    R22, 0 ;TESTE------------
    CBI     PORTB, PB3;TESTE-----------

    SBRC    R22, 1 ;TESTE------------
    SBI     PORTB, PB4;TESTE-----------
    SBRS    R22, 1 ;TESTE------------
    CBI     PORTB, PB4;TESTE-----------

    SBRC    R22, 2 ;TESTE------------
    SBI     PORTB, PB5;TESTE-----------
    SBRS    R22, 2 ;TESTE------------
    CBI     PORTB, PB5;TESTE-----------

    SBRC    R22, 3 ;TESTE------------
    SBI     PORTB, PB6;TESTE-----------
    SBRS    R22, 3 ;TESTE------------
    CBI     PORTB, PB6;TESTE-----------

    SBRC    R22, 4 ;TESTE------------
    SBI     PORTB, PB7;TESTE-----------
    SBRS    R22, 4 ;TESTE------------
    CBI     PORTB, PB7;TESTE-----------

ON_HEAE:
    LDI     R17, 0B00000100
    SBIC    PINC, PC2 ; CHECA: SE O BOTÃO A NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     ON_M ; SE CHEGOU AQUI É PQ APERTOU O BOTAO A,  ENTAO VAI PRA O PROXIMO ESTADO DA SEQUENCIA DE AJUSTE DO AGENDAMENTO
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     ON_HEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

ON_M:
    SBIC    PINC, PC2 ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO
    JMP     ON_M ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    CBI     PORTD, PD0 ; TESTE ------------------------------------
    SBI     PORTD, PD1 ; TESTE ------------------------------------
    SBI     PORTC, PC5 ; TESTE ------------------------------------
    CBI     PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE MINUTO AGENDAMENTO INICIO--------------------

    SBRC    R23, 0 ;TESTE------------
    SBI     PORTD, PD2;TESTE-----------
    SBRS    R23, 0 ;TESTE------------
    CBI     PORTD, PD2;TESTE-----------

    SBRC    R23, 1 ;TESTE------------
    SBI     PORTD, PD3;TESTE-----------
    SBRS    R23, 1 ;TESTE------------
    CBI     PORTD, PD3;TESTE-----------

    SBRC    R23, 2 ;TESTE------------
    SBI     PORTD, PD4;TESTE-----------
    SBRS    R23, 2 ;TESTE------------
    CBI     PORTD, PD4;TESTE-----------

    SBRC    R23, 3 ;TESTE------------
    SBI     PORTD, PD5;TESTE-----------
    SBRS    R23, 3 ;TESTE------------
    CBI     PORTD, PD5;TESTE-----------

    SBRC    R23, 4 ;TESTE------------
    SBI     PORTD, PD6;TESTE-----------
    SBRS    R23, 4 ;TESTE------------
    CBI     PORTD, PD6;TESTE-----------

    SBRC    R23, 5 ;TESTE------------
    SBI     PORTD, PD7;TESTE-----------
    SBRS    R23, 5 ;TESTE------------
    CBI     PORTD, PD7;TESTE-----------

ON_MEAE:
    LDI     R17, 0B00000101
    SBIC    PINC, PC2 ; CHECA: SE O BOTÃO A NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     WEEK_ON ; SE CHEGOU AQUI É PQ APERTOU O BOTAO A,  ENTAO VAI PRA O PROXIMO ESTADO DA SEQUENCIA DE AJUSTE DO AGENDAMENTO
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     ON_MEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

WEEK_ON:
    SBIC    PINC, PC2 ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO
    JMP     WEEK_ON ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    SBI     PORTD, PD0 ; TESTE ------------------------------------
    SBI     PORTD, PD1 ; TESTE ------------------------------------
    SBI     PORTC, PC5 ; TESTE ------------------------------------
    CBI     PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE DIA AGENDAMENTO INICIO--------------------
    SBRC    R24, 0 ;TESTE------------
    SBI     PORTB, PB0;TESTE-----------
    SBRS    R24, 0 ;TESTE------------
    CBI     PORTB, PB0;TESTE-----------

    SBRC    R24, 1 ;TESTE------------
    SBI     PORTB, PB1;TESTE-----------
    SBRS    R24, 1 ;TESTE------------
    CBI     PORTB, PB1;TESTE-----------

    SBRC    R24, 2 ;TESTE------------
    SBI     PORTB, PB2;TESTE-----------
    SBRS    R24, 2 ;TESTE------------
    CBI     PORTB, PB2;TESTE-----------

WEEK_ONEAE:
    LDI     R17, 0B00000110
    SBIC    PINC, PC2 ; CHECA: SE O BOTÃO A NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     JUSTE_AGENDAMENTO_FIM ; SE CHEGOU AQUI É PQ APERTOU O BOTAO A,  ENTAO VAI PRA O PROXIMO ESTADO DA SEQUENCIA DE AJUSTE DO AGENDAMENTO
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     WEEK_ONEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

OFF_H:
    SBIC    PINC, PC2 ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO
    JMP     OFF_H ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    CBI     PORTD, PD0 ; TESTE ------------------------------------
    CBI     PORTD, PD1 ; TESTE ------------------------------------
    CBI     PORTC, PC5 ; TESTE ------------------------------------
    SBI     PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE HORA AGENDAMENTO FIM--------------------

    SBRC    R25, 0 ;TESTE------------
    SBI     PORTB, PB3;TESTE-----------
    SBRS    R25, 0 ;TESTE------------
    CBI     PORTB, PB3;TESTE-----------

    SBRC    R25, 1 ;TESTE------------
    SBI     PORTB, PB4;TESTE-----------
    SBRS    R25, 1 ;TESTE------------
    CBI     PORTB, PB4;TESTE-----------

    SBRC    R25, 2 ;TESTE------------
    SBI     PORTB, PB5;TESTE-----------
    SBRS    R22, 2 ;TESTE------------
    CBI     PORTB, PB5;TESTE-----------

    SBRC    R25, 3 ;TESTE------------
    SBI     PORTB, PB6;TESTE-----------
    SBRS    R25, 3 ;TESTE------------
    CBI     PORTB, PB6;TESTE-----------

    SBRC    R25, 4 ;TESTE------------
    SBI     PORTB, PB7;TESTE-----------
    SBRS    R25, 4 ;TESTE------------
    CBI     PORTB, PB7;TESTE-----------

OFF_HEAE:
    LDI     R17, 0B00000111
    SBIC    PINC, PC2 ; CHECA: SE O BOTÃO A NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     OFF_M ; SE CHEGOU AQUI É PQ APERTOU O BOTAO A,  ENTAO VAI PRA O PROXIMO ESTADO DA SEQUENCIA DE AJUSTE DO AGENDAMENTO
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     OFF_HEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

OFF_M:
    SBIC    PINC, PC2 ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO
    JMP     OFF_M ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    SBI     PORTD, PD0 ; TESTE ------------------------------------
    CBI     PORTD, PD1 ; TESTE ------------------------------------
    CBI     PORTC, PC5 ; TESTE ------------------------------------
    SBI     PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE MINUTO AGENDAMENTO INICIO--------------------
    SBRC    R26, 0 ;TESTE------------
    SBI     PORTD, PD2;TESTE-----------
    SBRS    R26, 0 ;TESTE------------
    CBI     PORTD, PD2;TESTE-----------

    SBRC    R26, 1 ;TESTE------------
    SBI     PORTD, PD3;TESTE-----------
    SBRS    R26, 1 ;TESTE------------
    CBI     PORTD, PD3;TESTE-----------

    SBRC    R26, 2 ;TESTE------------
    SBI     PORTD, PD4;TESTE-----------
    SBRS    R26, 2 ;TESTE------------
    CBI     PORTD, PD4;TESTE-----------

    SBRC    R26, 3 ;TESTE------------
    SBI     PORTD, PD5;TESTE-----------
    SBRS    R26, 3 ;TESTE------------
    CBI     PORTD, PD5;TESTE-----------

    SBRC    R26, 4 ;TESTE------------
    SBI     PORTD, PD6;TESTE-----------
    SBRS    R26, 4 ;TESTE------------
    CBI     PORTD, PD6;TESTE-----------

    SBRC    R26, 5 ;TESTE------------
    SBI     PORTD, PD7;TESTE-----------
    SBRS    R23, 5 ;TESTE------------
    CBI     PORTD, PD7;TESTE-----------

OFF_MEAE:
    LDI     R17, 0B00001000
    SBIC    PINC, PC2 ; CHECA: SE O BOTÃO A NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     WEEK_OFF ; SE CHEGOU AQUI É PQ APERTOU O BOTAO A,  ENTAO VAI PRA O PROXIMO ESTADO DA SEQUENCIA DE AJUSTE DO AGENDAMENTO
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     OFF_MEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

WEEK_OFF:
    SBIC    PINC, PC2 ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO
    JMP     WEEK_OFF ; SO PRA GARANTIR QUE O BOTAO A FOI SOLTO

    ;TESTE LED DE ESTADO--------------------
    CBI     PORTD, PD0 ; TESTE ------------------------------------
    SBI     PORTD, PD1 ; TESTE ------------------------------------
    CBI     PORTC, PC5 ; TESTE ------------------------------------
    SBI     PORTC, PC4 ; TESTE ------------------------------------

    ;TESTE LED DE DIA AGENDAMENTO FIM--------------------
    SBRC    R27, 0 ;TESTE------------
    SBI     PORTB, PB0;TESTE-----------
    SBRS    R27, 0 ;TESTE------------
    CBI     PORTB, PB0;TESTE-----------

    SBRC    R27, 1 ;TESTE------------
    SBI     PORTB, PB1;TESTE-----------
    SBRS    R27, 1 ;TESTE------------
    CBI     PORTB, PB1;TESTE-----------

    SBRC    R27, 2 ;TESTE------------
    SBI     PORTB, PB2;TESTE-----------
    SBRS    R27, 2 ;TESTE------------
    CBI     PORTB, PB2;TESTE-----------

WEEK_OFFEAE:
    LDI     R17, 0B00001001
    SBIC    PINC, PC2 ; CHECA: SE O BOTÃO A NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     RUN ; SE CHEGOU AQUI É PQ APERTOU O BOTAO A,  ENTAO O AJUSTE DE AGENDAMENTO ACABOU. VOLTA PARA O ESTADO RUN
    SBIC    PINC, PC1 ; CHECA: SE O BOTÃO UP NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     INCREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO UP, ENTAO VAI PRA O ESTADO DE INCREMENTO
    SBIC    PINC, PC0 ; CHECA: SE O BOTÃO DOWN NAO ESTIVER APERTADO, PULA A PROXIMA INSTRUCAO
    JMP     DECREMENTO ; SE CHEGOU AQUI É PQ APERTOU O BOTAO DOWN, ENTAO VAI PRA O ESTADO DE DECREMENTO
    JMP     WEEK_OFFEAE ; SE CHEGOU AQUÍ É PQ NAO APERTOU NADA. VOLTA ATÉ APERTAR

;-----ESTADO DE INCREMENTO: PULA PARA O INCREMENTO DE ACORDO COM O PONTEIRO-------
INCREMENTO:
    SBIC    PINC, PC1 ; SO PRA GARANTIR QUE O BOTAO UP FOI SOLTO
    JMP     INCREMENTO ; SO PRA GARANTIR QUE O BOTAO UP FOI SOLTO

    CPI     R17, 0B00000001
    BREQ    INC_REG_HOUR_RA  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 
    JMP     EAE2

INC_REG_HOUR_RA: 
    JMP INC_REG_HOUR_R

EAE2:
    CPI     R17, 0B00000010
    BREQ    INC_REG_MIN_RA
    JMP     EAE3

INC_REG_MIN_RA:
    JMP     INC_REG_MIN_R  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE3:
    CPI     R17, 0B00000011
    BREQ    INC_REG_WEEK_RA
    JMP     EAE4

INC_REG_WEEK_RA: 
    JMP     INC_REG_WEEK_R  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE4:
    CPI     R17, 0B00000100
    BREQ    INC_REG_HOUR_ONA
    JMP     EAE5

INC_REG_HOUR_ONA: 
    JMP     INC_REG_HOUR_ON  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE5:
    CPI     R17, 0B00000101
    BREQ    INC_REG_MIN_ONA
    JMP     EAE6
INC_REG_MIN_ONA: 
    JMP     INC_REG_MIN_ON  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE6:
    CPI     R17, 0B00000110
    BREQ    INC_REG_WEEK_ONA
    JMP     EAE7

INC_REG_WEEK_ONA: 
    JMP     INC_REG_WEEK_ON  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE7:
    CPI R17, 0B00000111
    BREQ INC_REG_HOUR_OFFA
    JMP EAE8

INC_REG_HOUR_OFFA: 
    JMP     INC_REG_HOUR_OFF  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE8:
    CPI     R17, 0B00001000
    BREQ    INC_REG_MIN_OFFA
    JMP     EAE9

INC_REG_MIN_OFFA: 
    JMP     INC_REG_MIN_OFF  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE9:
    CPI     R17, 0B00001001
    BREQ    INC_REG_WEEK_OFFA

INC_REG_WEEK_OFFA: 
    JMP     INC_REG_WEEK_OFF  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

;-----ESTADO DE DECREMENTO: PULA PARA O INCREMENTO DE ACORDO COM O PONTEIRO-------
DECREMENTO:
    SBIC    PINC, PC0 ; SO PRA GARANTIR QUE O BOTAO DOWN FOI SOLTO
    JMP     DECREMENTO ; SO PRA GARANTIR QUE O BOTAO DOWN FOI SOLTO

    CPI     R17, 0B00000001
    BREQ    DEC_REG_HOUR_RA
    JMP     EAE10

DEC_REG_HOUR_RA: 
    JMP     DEC_REG_HOUR_R  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE10:
    CPI     R17, 0B00000010
    BREQ    DEC_REG_MIN_RA
    JMP     EAE11

DEC_REG_MIN_RA: 
    JMP     DEC_REG_MIN_R  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE11:
    CPI     R17, 0B00000011
    BREQ    DEC_REG_WEEK_RA
    JMP     EAE12

DEC_REG_WEEK_RA: 
    JMP     DEC_REG_WEEK_R  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE12:
    CPI     R17, 0B00000100
    BREQ    DEC_REG_HOUR_ONA
    JMP     EAE13

DEC_REG_HOUR_ONA: 
    JMP     DEC_REG_HOUR_ON  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE13:
    CPI     R17, 0B00000101
    BREQ    DEC_REG_MIN_ONA
    JMP     EAE14

DEC_REG_MIN_ONA: 
    JMP DEC_REG_MIN_ON  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE14:
    CPI     R17, 0B00000110
    BREQ    DEC_REG_WEEK_ONA
    JMP     EAE15

DEC_REG_WEEK_ONA: 
    JMP DEC_REG_WEEK_ON  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE15:
    CPI     R17, 0B00000111
    BREQ    DEC_REG_HOUR_OFFA
    JMP     EAE16

DEC_REG_HOUR_OFFA:
    JMP     DEC_REG_HOUR_OFF  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE16:
    CPI     R17, 0B00001000
    BREQ    DEC_REG_MIN_OFFA
    JMP     EAE17

DEC_REG_MIN_OFFA:
    JMP     DEC_REG_MIN_OFF  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

EAE17:
    CPI     R17, 0B00001001
    BREQ    DEC_REG_WEEK_OFFA

DEC_REG_WEEK_OFFA: 
    JMP     DEC_REG_WEEK_OFF  ; TIVE QUE FAZER ESSE "AJUSTE", PQ O BREQ TEM LIMITAÇÃO DE TAMANHO DE PULO. 

;-------------LABELS DE INCREMENTO DOS REGISTRADORES-------------------------;
;PS.: ANTES DE INCREMENTAR, CHECA SE CHEGOU AO LIMITE SUPERIOR OU INFERIOR. CASO SIM, FAZ A ALTERAÇÃO NECESSÁRIA

;----INCREMENTA A HORA DO RELOGIO E VOLTA ----;
INC_REG_HOUR_R:
    CPI     R19, 0B00010111 ; COMPARA A HORA COM 23
    BREQ    AUX_INC_HORA_R; SE A HORA ERA 23, VAI PRA 0.
    INC     R19
    JMP     TIMER_H

AUX_INC_HORA_R:
    LDI     R19, 0B00000000 ; SE A HORA ERA 23, VAI PRA 0.
    JMP     TIMER_H

;----INCREMENTA O MINUTO DO RELOGIO E VOLTA ----;
INC_REG_MIN_R:
    CPI     R20, 0B00111011 ; COMPARA O MINUTO COM 59
    BREQ    AUX_INC_MIN_R ; SE O MINUTO ERA 59, VAI PRA 0
    INC     R20
    JMP     TIMER_M

AUX_INC_MIN_R:
    LDI     R20, 0B00000000 ; SE O MINUTO ERA 59, VAI PRA 0.
    JMP     TIMER_M

;----INCREMENTA O DIA DO RELOGIO E VOLTA ----;
INC_REG_WEEK_R:
    CPI     R21, 0B00000111 ; COMPARA O DIA COM 7
    BREQ    AUX_INC_WEEK_R ; SE O DIA ERA 7, VAI PRA 1
    INC     R21
    JMP     WEEK

AUX_INC_WEEK_R:
    LDI     R21, 0B00000001 ; SE O DIA ERA 7, VAI PRA 1
    JMP     WEEK

;----INCREMENTA A HORA INICIAL DO AGENDAMENTO E VOLTA ----;
INC_REG_HOUR_ON:
    CPI     R22, 0B00010111 ; COMPARA A HORA COM 23
    BREQ    AUX_INC_HORA_ON; SE A HORA ERA 23, VAI PRA 0.
    INC     R22
    JMP     ON_H

AUX_INC_HORA_ON:
    LDI     R22, 0B00000000 ; SE A HORA ERA 23, VAI PRA 0.
    JMP     ON_H

;----INCREMENTA O MINUTO INICIAL DO AGENDAMENTO E VOLTA ----;
INC_REG_MIN_ON:
    CPI     R23, 0B00111011 ; COMPARA O MINUTO COM 59
    BREQ    AUX_INC_MIN_ON ; SE O MINUTO ERA 59, VAI PRA 0
    INC     R23
    JMP     ON_M

AUX_INC_MIN_ON:
    LDI     R23, 0B00000000 ; SE O MINUTO ERA 59, VAI PRA 0.
    JMP     ON_M

;----INCREMENTA O DIA INICAL DO AGENDAMENTO E VOLTA ----;
INC_REG_WEEK_ON:
    CPI     R24, 0B00000111 ; COMPARA O DIA COM 7
    BREQ    AUX_INC_WEEK_ON ; SE O DIA ERA 7, VAI PRA 1
    INC     R24
    JMP     WEEK_ON

AUX_INC_WEEK_ON:
    LDI     R24, 0B00000001 ; SE O DIA ERA 7, VAI PRA 1
    JMP     WEEK_ON

;----INCREMENTA A HORA FINAL DO AGENDAMENTO E VOLTA ----;
INC_REG_HOUR_OFF:
    CPI     R25, 0B00010111 ; COMPARA A HORA COM 23
    BREQ    AUX_INC_HORA_OFF; SE A HORA ERA 23, VAI PRA 0.
    INC     R25
    JMP     OFF_H

AUX_INC_HORA_OFF:
    LDI     R25, 0B00000000 ; SE A HORA ERA 23, VAI PRA 0.
    JMP     OFF_H

;----INCREMENTA O MINUTO FINAL DO AGENDAMENTO E VOLTA ----;
INC_REG_MIN_OFF:
    CPI     R26, 0B00111011 ; COMPARA O MINUTO COM 59
    BREQ    AUX_INC_MIN_OFF ; SE O MINUTO ERA 59, VAI PRA 0
    INC     R26
    JMP     OFF_M

AUX_INC_MIN_OFF:
    LDI     R26, 0B00000000 ; SE O MINUTO ERA 59, VAI PRA 0.
    JMP     OFF_M


;----INCREMENTA O DIA FINAL DO AGENDAMENTO E VOLTA ----;
INC_REG_WEEK_OFF:
    CPI     R27, 0B00000111 ; COMPARA O DIA COM 7
    BREQ    AUX_INC_WEEK_OFF ; SE O DIA ERA 7, VAI PRA 1
    INC     R27
    JMP     WEEK_OFF

AUX_INC_WEEK_OFF:
    LDI     R27, 0B00000001 ; SE O DIA ERA 7, VAI PRA 1
    JMP     WEEK_OFF

;-------------LABELS DE DECREMENTO DOS REGISTRADORES-------------------------;
;PS.: ANTES DE DECREMENTAR, CHECA SE CHEGOU AO LIMITE SUPERIOR OU INFERIOR. CASO SIM, FAZ A ALTERAÇÃO NECESSÁRIA

;----DECREMENTA A HORA DO RELOGIO E VOLTA ----;
DEC_REG_HOUR_R:
    CPI     R19, 0B00000000 ; COMPARA A HORA COM 0
    BREQ    AUX_DEC_HORA_R; SE A HORA ERA 0, VAI PRA 23.
    DEC     R19
    JMP     TIMER_H

AUX_DEC_HORA_R:
    LDI     R19, 0B00010111; SE A HORA ERA 0, VAI PRA 23.
    JMP     TIMER_H

;----DECREMENTA O MINUTO DO RELOGIO E VOLTA ----;
DEC_REG_MIN_R:
    CPI     R20, 0B00000000 ; COMPARA O MINUTO COM 0
    BREQ    AUX_DEC_MIN_R ; SE O MINUTO ERA 0, VAI PRA 59
    DEC     R20
    JMP     TIMER_M

AUX_DEC_MIN_R:
    LDI     R20, 0B00111011 ; SE O MINUTO ERA 0, VAI PRA 59.
    JMP     TIMER_M

;----DECREMENTA O DIA DO RELOGIO E VOLTA ----;
DEC_REG_WEEK_R:
    CPI     R21, 0B00000001 ; COMPARA O DIA COM 1
    BREQ    AUX_DEC_WEEK_R ; SE O DIA ERA 1, VAI PRA 7
    DEC     R21
    JMP     WEEK

AUX_DEC_WEEK_R:
    LDI     R21, 0B00000111 ; SE O DIA ERA 1, VAI PRA 7
    JMP     WEEK

;----DECREMENTA A HORA INICIAL DO AGENDAMENTO E VOLTA ----;
DEC_REG_HOUR_ON:
    CPI     R22, 0B00000000 ; COMPARA A HORA COM 0
    BREQ    AUX_DEC_HORA_ON; SE A HORA ERA 0, VAI PRA 23.
    DEC     R22
    JMP     ON_H

AUX_DEC_HORA_ON:
    LDI     R22, 0B00010111; SE A HORA ERA 0, VAI PRA 23.
    JMP     ON_H

;----DECREMENTA O MINUTO INICIAL DO AGENDAMENTO E VOLTA ----;
DEC_REG_MIN_ON:
    CPI     R23, 0B00000000 ; COMPARA O MINUTO COM 0
    BREQ    AUX_DEC_MIN_ON ; SE O MINUTO ERA 0, VAI PRA 59
    DEC     R23
    JMP     ON_M

AUX_DEC_MIN_ON:
    LDI     R23, 0B00111011 ; SE O MINUTO ERA 0, VAI PRA 59.
    JMP     ON_M

;----DECREMENTA O DIA INICAL DO AGENDAMENTO E VOLTA ----;
DEC_REG_WEEK_ON:
    CPI     R24, 0B00000001 ; COMPARA O DIA COM 1
    BREQ    AUX_DEC_WEEK_ON ; SE O DIA ERA 1, VAI PRA 7
    DEC     R24
    JMP     WEEK_ON

AUX_DEC_WEEK_ON:
    LDI     R24, 0B00000111 ; SE O DIA ERA 1, VAI PRA 7
    JMP     WEEK_ON

;----DECREMENTA A HORA FINAL DO AGENDAMENTO E VOLTA ----;
DEC_REG_HOUR_OFF:
    CPI     R25, 0B00000000 ; COMPARA A HORA COM 0
    BREQ    AUX_DEC_HORA_OFF; SE A HORA ERA 0, VAI PRA 23.
    DEC     R25
    JMP     OFF_H

AUX_DEC_HORA_OFF:
    LDI     R25, 0B00010111; SE A HORA ERA 0, VAI PRA 23.
    JMP     OFF_H

;----DECREMENTA O MINUTO FINAL DO AGENDAMENTO E VOLTA ----;
DEC_REG_MIN_OFF:
    CPI     R26, 0B00000000 ; COMPARA O MINUTO COM 0
    BREQ    AUX_DEC_MIN_OFF ; SE O MINUTO ERA 0, VAI PRA 59
    DEC     R26
    JMP     OFF_M

AUX_DEC_MIN_OFF:
    LDI     R26, 0B00111011 ; SE O MINUTO ERA 0, VAI PRA 59.
    JMP     OFF_M

;----DECREMENTA O DIA FINAL DO AGENDAMENTO E VOLTA ----;
DEC_REG_WEEK_OFF:
    CPI     R27, 0B00000001 ; COMPARA O DIA COM 1
    BREQ    AUX_DEC_WEEK_OFF ; SE O DIA ERA 1, VAI PRA 7
    DEC     R27
    JMP     WEEK_OFF

AUX_DEC_WEEK_OFF:
    LDI     R27, 0B00000111 ; SE O DIA ERA 1, VAI PRA 7
    JMP     WEEK_OFF